# Generated by Django 4.2.21 on 2025-05-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_responses/', verbose_name='Изображение ответа'),
        ),
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/', verbose_name='Изображение'),
        ),
    ]
